# Generated by Django 5.2 on 2026-05-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cuota_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='requiere_aval',
        ),
        migrations.AddField(
            model_name='contrato',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del servicio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='direccion_cliente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección del cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_cliente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Empresa del cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=200, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Garantía'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=40, verbose_name='Teléfono del cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiempo_entrega',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiempo de entrega'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del cliente'),
        ),
    ]
