# Generated by Django 5.2 on 2026-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0002_remove_contrato_cuota_mantenimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tiempo_entrega',
        ),
        migrations.AddField(
            model_name='contrato',
            name='dias_entrega',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de entrega'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='meses_garantia',
            field=models.PositiveIntegerField(default=0, verbose_name='Meses de garantía'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto total del servicio'),
        ),
    ]
