# Generated by Django 5.2 on 2026-05-11 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0003_remove_contrato_forma_pago_remove_contrato_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='vigencia_dias',
            field=models.PositiveIntegerField(choices=[(15, '15 días'), (30, '30 días')], default=30, verbose_name='Días de vigencia'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dias_entrega',
            field=models.PositiveIntegerField(default=30, verbose_name='Días de entrega'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='meses_garantia',
            field=models.PositiveIntegerField(choices=[(3, '3 meses'), (6, '6 meses'), (12, '12 meses')], default=6, verbose_name='Meses de garantía'),
        ),
    ]
